# Generated by Django 3.0.7 on 2020-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20200911_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('NONCASH', 'Электронно')], default='CASH', max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
